"""Export CRDs generated by the pinned upstream API using temporary CRD-only RBAC.

Development bootstrap only. The bootstrap role and binding are always removed.
Review the exported definitions before incorporating them into installation.
"""
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    config = json.loads((ROOT / 'config/config.json').read_text(encoding='utf-8-sig'))
    deployment = config['deployment']
    if not deployment['enable_mutations'] or config['terraform']['environment'] != 'dev':
        raise RuntimeError('Requires explicitly enabled development mutations')
    namespace, release = deployment['namespace'], deployment['release']
    kube = ['kubectl', '--context', deployment['kube_context']]

    def run(arguments, payload=None, optional=False):
        response = subprocess.run(kube + arguments, input=payload, capture_output=True, text=True)
        if response.returncode and not optional:
            raise RuntimeError('CRD bootstrap failed; review local Kubernetes status')
        return response.stdout

    cluster = json.loads(run(['config', 'view', '--minify', '-o', 'json']))['clusters'][0]['cluster']
    if cluster['server'] != deployment['kube_api_server'] or cluster.get('insecure-skip-tls-verify'):
        raise RuntimeError('Kubernetes target identity mismatch')
    name = release + '-temporary-crd-bootstrap'
    role = {'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'ClusterRole', 'metadata': {'name': name},
        'rules': [{'apiGroups': ['apiextensions.k8s.io'], 'resources': ['customresourcedefinitions'],
            'verbs': ['get', 'list', 'create', 'update', 'patch']}]}
    binding = {'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'ClusterRoleBinding', 'metadata': {'name': name},
        'roleRef': {'apiGroup': 'rbac.authorization.k8s.io', 'kind': 'ClusterRole', 'name': name},
        'subjects': [{'kind': 'ServiceAccount', 'name': release, 'namespace': namespace}]}
    try:
        run(['apply', '-f', '-'], json.dumps({'apiVersion': 'v1', 'kind': 'List', 'items': [role, binding]}))
        run(['-n', namespace, 'rollout', 'restart', 'deployment/' + release + '-apiserver'])
        run(['-n', namespace, 'rollout', 'status', 'deployment/' + release + '-apiserver', '--timeout=180s'])
        resources = json.loads(run(['get', 'crds', '-o', 'json']))['items']
        resources = [item for item in resources if item['spec']['group'] == 'michelangelo.api']
        if not resources:
            raise RuntimeError('Upstream API did not register its CRDs')
        for resource in resources:
            resource.pop('status', None)
            resource['metadata'] = {'name': resource['metadata']['name']}
        directory = ROOT / 'deploy/crds'
        directory.mkdir(exist_ok=True)
        for resource in resources:
            (directory / (resource['metadata']['name'] + '.json')).write_text(json.dumps(resource, indent=2) + '\n')
        print(f'Exported {len(resources)} upstream-generated CRDs without cluster metadata; review before publishing.')
    finally:
        run(['delete', 'clusterrolebinding', name, '--ignore-not-found'], optional=True)
        run(['delete', 'clusterrole', name, '--ignore-not-found'], optional=True)


if __name__ == '__main__':
    try:
        main()
    except (KeyError, ValueError, OSError, RuntimeError):
        raise SystemExit('CRD bootstrap failed; temporary bootstrap permissions removed when API access remained available')
